version: '3.8'

services:
  # Frontend (React)
  snapbox:
    container_name: snapbox
    restart: always
    build:
      context: .
      dockerfile: front/Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: true
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app  # Alterei o volume para /app, que é o diretório padrão do container
    env_file:
      - ./front/.env.dev  

  # Banco de Dados (PostgreSQL)
  db_snapbox:
    container_name: db_snapbox
    image: postgres:14.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: snapbox  # Nome do banco a ser criado
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./back/.env.dev  # O .env.dev do back-end, que inclui as variáveis de banco de dados
    # Removi o comando 'postgres', pois a imagem do PostgreSQL já inicializa automaticamente

  # Backend (Express)
  back:
    container_name: back
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    env_file:
      - ./back/.env.dev  
    volumes:
      - ./back:/app  # Alterei o volume para /app, que é o diretório padrão do container
    depends_on:
      - db_snapbox

volumes:
  front:
