
services: 

  estacoes:
    container_name: estacoes
    build: 
      context: .
      dockerfile: back/Dockerfile
    volumes:
      - ./back:/back:delegated
    ports:
      - 8021:8021
    env_file:
      - .env.dev
    # links:
      # - redis_base
    depends_on:
      - db_estacoes

  db_estacoes: 
    container_name: db_estacoes
    image: postgres:14.0-alpine
    volumes: 
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - 5071:5071
    env_file:
      - .env.dev
    command: -p 5071

  # redis_base:
  #   container_name: redis_base
  #   image: 'redis:latest'
  #   ports:
  #     - '6383:6383'
  #   command: redis-server --port 6383 --requirepass BlEnEvOlferOInElTaRYMiTrisMATi
  #   volumes: 
  #     - ./redis_base_data:/data


  front_estacoes: 
    container_name: front_estacoes
    restart: always
    # command: npm start
    build:
      context: .
      dockerfile: front/Dockerfile
    environment:  
      CHOKIDAR_USEPOLLING: true
    ports:
      - "3011:3011"
    volumes:
      - ./front:/front
      - '/front/node_modules'
    env_file:
      - .env.dev


volumes:
  postgres_data:
    driver: local
  redis_base:
    driver: local
