version: '3.8'

services:
  # Frontend (React)
  snapbox:
    container_name: snapbox
    restart: always
    build:
      context: .
      dockerfile: front/Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: true
    ports:
      - "3000:3000"
    volumes:
      - ./front:/front
    env_file:
      - ./front/.env.dev  # ✅ caminho ajustado

  # Banco de Dados (PostgreSQL)
  db_snapbox:
    container_name: db_snapbox
    image: postgres:14.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./back/.env.dev  # ✅ ou crie um .env específico para o banco
    command: postgres

  # Backend (Express)
  back:
    container_name: back
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    env_file:
      - ./back/.env.dev  # ✅ caminho ajustado
    volumes:
      - ./back:/back
    depends_on:
      - db_snapbox

volumes:
  front:
